src/config/chainData.ts

increase deposit limit to 10000 ETH

Update chainData.ts - increase deposit limit to 10000 ETH

---

src/components/Disclaimer.tsx
src/config/chainData.ts

1. Set max deposit to 0 (temporarily)
2. update banner

Set max deposit to 0 (temporarily)

---

.env.example
package.json
pnpm-lock.yaml
src/config/chainData.ts
src/config/constants.ts
src/config/env.ts
src/containers/Footer.tsx
src/types/config.ts
src/utils/sdk.ts

feat: new RPC url and SDK v0.1.21

---

src/components/PoolAccountTable.tsx
src/containers/Modals/PoolDetails/index.tsx

fixes #23
[Screencast from 2025-06-02 14-01-43.webm](https://github.com/user-attachments/assets/3d710684-71a8-4d83-b701-b6bb05c0e9a9)

feat: add pool accounts txid

---

src/containers/CreateHistoryFile.tsx
src/containers/SeedPhraseForm.tsx

fixes #31
https://github.com/user-attachments/assets/609bb83a-2488-41e3-a530-9744a52d5965

feat: verify seedphrase before creating account

---

src/components/AssetSelect.tsx
src/config/chainData.ts

Adds stablecoins support for sepolia testnet

Testnet stablecoin pools

---

src/app/api/token/route.ts
src/components/Menu.tsx
src/components/StatusChip.tsx
src/containers/Modals/ActivityDetails/Transaction.tsx
src/containers/Modals/GeneratingZkProof/AnimatedTree.tsx
src/containers/Modals/GeneratingZkProof/Generating.tsx
src/containers/SeedPhraseForm.tsx
src/hooks/index.ts
src/hooks/useCircuitPreloader.ts
src/hooks/useDeposit.ts
src/hooks/useExit.ts
src/hooks/useWithdraw.ts
src/hooks/useZKProofWorker.ts
src/instrumentation-client.ts
src/providers/CircuitProvider.tsx
src/providers/index.tsx
src/utils/clipboard.ts
src/utils/format.ts
src/utils/index.ts
src/utils/sdk.ts
src/workers/zkProofWorker.ts

- Replace direct DOM manipulation in AnimatedTree with React state
- Fix event log decoding by silently ignoring non-matching logs
The AnimatedTree component was causing "removeChild" errors by directly manipulating DOM elements via classList operations while React was managing the same elements. Replaced with useState-based animation control and proper cleanup to prevent state updates on unmounted components (sentry error https://0xbow.sentry.io/issues/6725818367/events/513ba66ea81f44bf9fdeb55facef6419/)
Event decoding was failing when trying to decode all transaction logs using a specific event ABI. Updated to silently ignore logs that don't match the expected signature instead of throwing errors.

fix: Resolve React DOM manipulation and event decoding errors

---

src/utils/relayerClient.ts

fix: pass extraGas

---

src/containers/Modals/Review/Review.tsx

fixed sUSDS token not giving ETH withdraw option
closes XXX

fixed susds withdrawal

---

src/containers/Modals/Review/FeeBreakdown.tsx
src/containers/Modals/Review/Review.tsx
src/contexts/QuoteContext.tsx
src/hooks/useRequestQuote.ts
src/types/relayer.ts

Fee Breakdown
- [X ] I have conducted a self-review of my code.
- [ X] I have conducted a QA.
- [ X] If it is a core feature, I have included comprehensive tests.

feat: fee breakdown

---

src/containers/Modals/Review/DataSection.tsx
src/containers/Modals/Review/FeeBreakdown.tsx

fix: improve fee breakdown copy

---

.github/workflows/build-test.yml

node 21.4 is not maintained more than a year, switched action to use the v22 lts

Updated node to LTS in lint action

---

src/__tests__/chainData.test.ts
src/__tests__/feeDisplayPrecision.test.ts
src/config/chainData.ts
src/containers/Modals/Review/DataSection.tsx
src/containers/Modals/Review/FeeBreakdown.tsx
src/containers/Modals/Review/PoolAccountSection.tsx
src/containers/Modals/Review/Review.tsx
src/hooks/useRequestQuote.ts

Fix double notification timer

---

src/containers/Modals/LinksSection.tsx
src/containers/Modals/Review/DataSection.tsx
src/containers/Modals/Review/FeeBreakdown.tsx
src/containers/Modals/Review/PoolAccountSection.tsx
src/containers/Modals/Review/Review.tsx

feat: new layout for review

---

src/components/ChainSelect.tsx
src/components/Menu.tsx
src/config/wagmiConfig.ts
src/containers/Modals/Review/DataSection.tsx
src/containers/Modals/Withdraw/WithdrawForm.tsx

feat: add ENS support

---

.github/workflows/build-test.yml
CHANGELOG.md
package.json
src/__tests__/chainData.test.ts
src/__tests__/feeDisplayPrecision.test.ts
src/components/ChainSelect.tsx
src/components/Menu.tsx
src/config/chainData.ts
src/config/wagmiConfig.ts
src/containers/Modals/LinksSection.tsx
src/containers/Modals/Review/DataSection.tsx
src/containers/Modals/Review/FeeBreakdown.tsx
src/containers/Modals/Review/PoolAccountSection.tsx
src/containers/Modals/Review/Review.tsx
src/containers/Modals/Withdraw/WithdrawForm.tsx
src/hooks/useRequestQuote.ts

- ENS support for user profile and withdrawals
- UX of withdrawal modal
- Bug with duplicated quote expiry notification

Release v1.4.0

---

CHANGELOG.md
package.json
src/containers/Modals/Review/DataSection.tsx
src/containers/Modals/Review/FeeBreakdown.tsx
src/containers/Modals/Review/PoolAccountSection.tsx

- Withdrawal modal fonts
- Gas token displayed value

Release v1.4.1

---

src/containers/Modals/Review/Review.tsx

Remove woeth from gas drop

---

src/app/layout.tsx
src/components/FeatureFlagInitializer.tsx
src/components/index.ts
src/hooks/useFeatureFlag.ts

Fix feature flag

---

src/containers/Modals/Deposit/DepositForm.tsx

fix: disable deposit if no ETH for gas

---

src/containers/Footer.tsx
src/containers/GlobalPool.tsx

Fix mobile footer

---

src/components/PoolAccountTable.tsx
src/containers/Welcome.tsx

fix: don't allow key derivation with coinbase wallet
